### ISSUE TITLE
paths to implement

### ISSUE THREAD

**Issue by arvind001** [JasonYao/university-video-meeter#3]
## Auth routes
- [x] /login
  - Functionality complete as of 34d713d30f425c39f239241648989c427747b948
  - Requires front-end overhaul
- [x] /register
  - Functionality complete as of 34d713d30f425c39f239241648989c427747b948
  - Requires front-end overhaul
- [ ] /reset
  - Requires domain name & mailgun setup
  - Initial GET route setup as of 3da9d8b9849f8f9a39858b2e2218fb6ce76a88f7
  - Requires POST handling
  - Requires front-end overhaul

## User Info routes
- [x] /optional
  - Functionality complete as of a98b29620ac81c24ccdc3ee483b1a7c85c9bae5c
  - Requires front-end overhaul
- [x] /ambassador
  - Functionality complete as of a98b29620ac81c24ccdc3ee483b1a7c85c9bae5c
  - Requires front-end overhaul

## Global site-wide routes
- [ ] /
  - Initial GET route stubbed as of d774b13a7dbbc95d2dc86429096dd068b2848788
  - Requires front-end overhaul
  - Requires changes to navbar to be valid links
- [ ] /about
  - Initial GET route stubbed as of adc8e5027df24226c06b1752845944c5b4d083fa
- [ ] /universities
  - Initial GET route stubbed as of adc8e5027df24226c06b1752845944c5b4d083fa
- [ ] /help
  - Initial GET route stubbed as of adc8e5027df24226c06b1752845944c5b4d083fa
- [ ] /universities/:slug/ambassadors
  - Initial GET route stubbed as of adc8e5027df24226c06b1752845944c5b4d083fa
  - Requires universities collection first
  - Views stub not complete

## Both User & Ambassador routes
- [ ] /schedule
  - Initial GET route stubbed as of adc8e5027df24226c06b1752845944c5b4d083fa
- [ ] /chat
  - Initial GET route stubbed as of adc8e5027df24226c06b1752845944c5b4d083fa
  - Initial global chatting environment is setup as of dd8699b4b4e778000a016c52ba59951882b3fe74

## User routes
- [ ] /dashboard
  - Initial setup as of d6e27a597412506e8f8e10ea3c124ffd73f3c330
- [ ] /settings
  - Initial setup as of a98b29620ac81c24ccdc3ee483b1a7c85c9bae5c
- [ ] /profile
  - Initial setup as of 4ab5bdbeb3043d38568876cf046cc61a354cefd0

## Ambassador routes
- [ ] /ambassadors/*profile-name-slug*
- [ ] /ambassadors/*profile-name-slug*/book (post and get)
- [ ] /ambassadors/*profile-name-slug*/calendar
